#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=4
export GH_REPO="bkafelov-aidoo/AIDOO-Whisper-Lite"
EXPECTED_IDENTITY="Developer ID Application: Aidoo Ltd. OOD"
EXPECTED_TEAM_ID="4KKVT2TUUA"

banner "AIDOO Whisper Lite · GitHub release credentials"

stage "GitHub access"
say "This wizard writes six repository secrets to $GH_REPO. It never prints or stores their values in the project."
for required_command in gh openssl base64; do
  if ! command -v "$required_command" >/dev/null 2>&1; then
    warn "$required_command is required. Install it and run this wizard again."
    exit 1
  fi
done
if ! gh auth status >/dev/null 2>&1; then
  warn "GitHub CLI is not authenticated. Run: gh auth login"
  exit 1
fi
if ! gh repo view "$GH_REPO" >/dev/null 2>&1; then
  warn "The authenticated GitHub account cannot access $GH_REPO."
  exit 1
fi
say "GitHub access is ready. Existing secrets with the same names will be replaced."
pause "Continue to the signing certificate?"

stage "Developer ID Application certificate"
say "Use the exact Developer ID Application identity for Aidoo Ltd. OOD, including its private key."
step "Open Keychain Access → My Certificates. Expand '$EXPECTED_IDENTITY ($EXPECTED_TEAM_ID)'."
step "Select the certificate and private key, then File → Export Items. Save a password-protected .p12 in a private local folder."
ask P12_PATH "Paste the full .p12 path (without quotes):"
if [[ ! -f "$P12_PATH" ]]; then
  warn "The .p12 file does not exist: $P12_PATH"
  exit 1
fi
ask_secret P12_PASSWORD "Enter the .p12 export password:"
if [[ -z "$P12_PASSWORD" ]]; then
  warn "The .p12 password cannot be empty."
  exit 1
fi
certificate_subject="$(P12_PASSWORD_ENV="$P12_PASSWORD" openssl pkcs12 -in "$P12_PATH" -clcerts -nokeys -passin env:P12_PASSWORD_ENV 2>/dev/null | openssl x509 -noout -subject 2>/dev/null || true)"
if [[ "$certificate_subject" != *"$EXPECTED_IDENTITY"* || "$certificate_subject" != *"$EXPECTED_TEAM_ID"* ]]; then
  warn "The file could not be verified as '$EXPECTED_IDENTITY ($EXPECTED_TEAM_ID)'."
  exit 1
fi
if ! P12_PASSWORD_ENV="$P12_PASSWORD" openssl pkcs12 -in "$P12_PATH" -nocerts -nodes -passin env:P12_PASSWORD_ENV 2>/dev/null | openssl pkey -noout >/dev/null 2>&1; then
  warn "The .p12 does not contain a readable private key for signing."
  exit 1
fi
certificate_base64="$(base64 < "$P12_PATH")"
keychain_password="$(openssl rand -base64 32 | tr -d '\n')"
set_secret APPLE_CERTIFICATE "$certificate_base64"
set_secret APPLE_CERTIFICATE_PASSWORD "$P12_PASSWORD"
set_secret KEYCHAIN_PASSWORD "$keychain_password"
unset certificate_base64 keychain_password P12_PASSWORD certificate_subject
say "The local .p12 was not changed or uploaded anywhere except the encrypted GitHub secret. Keep or delete your export according to your certificate backup policy."
pause "Continue to notarization credentials?"

stage "Apple notarization account"
say "Apple notarization uses an app-specific password, never your primary Apple Account password. Two-factor authentication must be enabled."
open_url "https://account.apple.com/account/manage"
step "In Sign-In and Security, open App-Specific Passwords. Generate one named 'AIDOO Whisper Lite notarization' and copy it."
ask_secret APPLE_ID_VALUE "Enter the Apple Account email used for notarization:"
ask_secret APPLE_PASSWORD_VALUE "Paste the generated app-specific password:"
if [[ -z "$APPLE_ID_VALUE" || -z "$APPLE_PASSWORD_VALUE" ]]; then
  warn "The Apple Account email and app-specific password are both required."
  exit 1
fi
set_secret APPLE_ID "$APPLE_ID_VALUE"
set_secret APPLE_PASSWORD "$APPLE_PASSWORD_VALUE"
set_secret APPLE_TEAM_ID "$EXPECTED_TEAM_ID"
unset APPLE_ID_VALUE APPLE_PASSWORD_VALUE
pause "Continue to the final verification?"

stage "Verify secret names"
required_secrets=(
  APPLE_CERTIFICATE
  APPLE_CERTIFICATE_PASSWORD
  KEYCHAIN_PASSWORD
  APPLE_ID
  APPLE_PASSWORD
  APPLE_TEAM_ID
)
secret_names="$(gh secret list --repo "$GH_REPO" --json name --jq '.[].name')"
missing_secrets=()
for secret in "${required_secrets[@]}"; do
  if ! grep -Fxq "$secret" <<< "$secret_names"; then
    missing_secrets+=("$secret")
  fi
done
if (( ${#missing_secrets[@]} )); then
  warn "GitHub did not report these secret names: ${missing_secrets[*]}"
  exit 1
fi
say "All six required GitHub secret names are present. Their values were not read back or displayed."
say "Do not create the release tag until the signed-build acceptance checklist is ready to run with a tester present."

finish
